-- Inserciones para usuario con rol Administrador

insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('PAUL GOMEZ','PGOMEZ', 'PGOMEZ@TRANSCOMA.COM', 'adminPaul', '13/09/2005' );
insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('ANTONI CASTELIS','ACASTELIS', 'ACASTELIS@TRANSCOMA.COM', 'FIFINE', '09/02/2002');
insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('JEREMIAS FOCHS','JFOCHS', 'JFOCHS1@TRANSCOMA.COM', 'JEREMIASF', '17/02/2003');
insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('TEDMUND COLLUMBELL','TCOLLUMBELL', 'TCOLLUMBELL2@TRANSCOMA.COM', 'TEDMUND', '18/07/2010');
insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('JOB HOULAGHAN','JHOULAGHAN', 'JHOULAGHAN3@TRANSCOMA.COM', 'JOB', '19/07/2001');
insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('ALEXIS VASQUES','AVASQUES', 'AVASQUES@TRANSCOMA.COM', 'ALEXIS', '06/01/2011');
insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('ABIUD RODAS','ARODAS', 'SCUTTLE5@TRANSCOMA.COM', 'ARODASRDS', '16/09/2015');
insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('ALISON GARCIA','AGARCIA', 'AGARCIA@TRANSCOMA.COM', 'ALISON', '12/07/2005');
insert into ADMINISTRADOR (_nombre,_nombreUsuario,_correo,_password,_fechaRegistro) values ('JESUS YEPES','JYEPES', 'JYEPES@TRANSCOMA.COM', 'JESUS', '12/07/2018');

-- Inserciones para usuario con rol Cliente/Compañia

insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('CUSTOMS MANAGEMENT CONSULTING, S.L.U.', 'cmc','cmc@customscm.es', 'DeV@2018', '17/06/2015', 1);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('SILVERTRANS TRANSITOS Y ADUANAS S.A.', 'silvertrans' ,'silvertrans@silvertrans.es', 'prueba', '29/10/2015', 2);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('TRANSCOMA GLOBAL LOGISTICS, SA','comercial', 'comercial@trancsomalogistics.com', '3squ3l3t0', '09/04/2002', 3);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('OLIMPIA LAPERE','OLAPERE', 'OLAPERE7@TRANSCOMA.COM', 'OLIMPIA', '23/01/2010',4);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('ETHEL STOURTON','ESTOURTON', 'ESTOURTON8@TRANSCOMA.COM', 'ETHEL', '14/08/2005',5);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('SANDOR GRONALLER','SGRONALLER', 'SGRONALLER9@TRANSCOMA.COM', 'SANDOR', '06/11/2004',6);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BARTOLEMO SENECHELL','BSENECHELL', 'BSENECHELL1B@TRANSCOMA.COM', 'BARTOLEMO', '03/06/2017',7);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('GARWIN RIPPEN','GRIPPEN', 'GRIPPEN1C@TRANSCOMA.COM', 'GARWIN', '01/05/2001',8);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BRODERIC FELLINI','BFELLINI', 'BFELLINI1D@TRANSCOMA.COM', 'BRODERIC', '29/08/2012',9);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('HALIMEDA LANCETTER','HLANCETTER', 'HLANCETTER1E@TRANSCOMA.COM', 'HALIMEDA', '06/11/2009',9);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('KESLIE JIME','KJIME', 'KJIME1F@TRANSCOMA.COM', 'KESLIE', '14/09/2006',9);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('CARLEY CUNNIFFE','CCUNNIFFE', 'CCUNNIFFE1G@TRANSCOMA.COM', 'CARLEY', '01/12/2000',9);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('OFFICE NATIONAL DE L ASSAINISSEMENT','ONATIONAL', 'ONATIONAL@TRANSCOMA.COM', 'DELPHINIA', '18/11/2016',9);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('ALONSO KLEINPLAC','AKLEINPLAC', 'AKLEINPLAC1I@TRANSCOMA.COM', 'ALONSO', '23/03/2005',9);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('TECNOLOGIA DE MONTAJES Y MANTENIMIENTOS S.A.','BMATHIAS', 'BMATHIAS1J@TRANSCOMA.COM', 'BLISSE', '15/12/2002',8);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('SANDRA ANTONIA','SANTONIA', 'SANTONIA@TRANSCOMA.COM', 'SHANDY', '10/12/2008',8);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('ANA ELENA','AELENA', 'AELENA@TRANSCOMA.COM', 'ANNA-DIANA', '05/05/2009',8);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('HOBIE KLAMPK','HKLAMPK', 'HKLAMPK1M@TRANSCOMA.COM', 'HOBIE', '29/05/2011',7);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('CARMELIA EYNON','CEYNON', 'CEYNON1N@TRANSCOMA.COM', 'CARMELIA', '09/09/2005',7);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('LOURDES MOYA','LMOYA', 'LMOYA@TRANSCOMA.COM', 'LORNE', '31/05/2004',7);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BELLA OAKMAN','BOAKMAN', 'BOAKMAN@TRANSCOMA.COM', 'BELLA', '13/04/2002',7);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BARNETT SUDDDARD','BSUDDDARD', 'BSUDDDARD1Q@TRANSCOMA.COM', 'BARNETT', '31/01/2017',7);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('GEORGEANNA ILIEVE','GILIEVE1R', 'GILIEVE1R@TRANSCOMA.COM', 'GEORGEANNA', '30/05/2001',6);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('CHELSAE CLENDENING','CCLENDENING1S', 'CCLENDENING1S@TRANSCOMA.COM', 'CHELSAE', '11/12/2016',6);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('SUTTON MATHES','SMATHES1T', 'SMATHES1T@TRANSCOMA.COM', 'SUTTON', '21/12/2012',6);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('FLUIDRA EXPORT, S.A.U.','FEXPORT', 'FEXPORT@TRANSCOMA.COM', 'BUCKY', '01/12/2011',5);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('TIEBOLD STINTON','TSTINTON1V', 'TSTINTON1V@TRANSCOMA.COM', 'TIEBOLD', '07/08/2001',5);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('CRISTIONNA WORSNUP','CWORSNUP1W', 'CWORSNUP1W@TRANSCOMA.COM', 'CRISTIONNA', '08/07/2007',5);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('ORTON STORK','OSTORK1X', 'OSTORK1X@TRANSCOMA.COM', 'ORTON', '06/09/2016',5);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BRIGG BAPTY','BBAPTY1Y', 'BBAPTY1Y@TRANSCOMA.COM', 'BRIGG', '15/03/2002',5);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('MUEBLES JUMAR S.L.','MJUMAR', 'MJUMAR@TRANSCOMA.COM', 'GERALDA', '29/09/2011',4);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('CINDERELLA WAYVILL','CWAYVILL20', 'CWAYVILL20@TRANSCOMA.COM', 'CINDERELLA', '03/01/2002',4);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('SHAWN JENNIONS','SJENNIONS21', 'SJENNIONS21@TRANSCOMA.COM', 'SHAWN', '13/02/2015',4);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BERNIE WORT','BWORT22', 'BWORT22@TRANSCOMA.COM', 'BERNIE', '03/03/2008',4);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BENDICK CONDLIFFE','BCONDLIFFE23', 'BCONDLIFFE23@TRANSCOMA.COM', 'BENDICK', '12/05/2013',3);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('ALPHONSO SYNKE','ASYNKE24', 'ASYNKE24@TRANSCOMA.COM', 'ALPHONSO', '21/04/2005',3);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('NICOL RIMBAULT','NRIMBAULT25', 'NRIMBAULT25@TRANSCOMA.COM', 'NICOL', '13/12/2015',3);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BERYL CRIGHTEN','BCRIGHTEN26', 'BCRIGHTEN26@TRANSCOMA.COM', 'BERYL', '03/08/2004',2);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('CARLOS TARGETTER','CTARGETTER27', 'CTARGETTER27@TRANSCOMA.COM', 'CHUCHO', '31/10/2009',2);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('BRODY MUM','BMUM28', 'BMUM28@TRANSCOMA.COM', 'BRODY', '08/06/2010',2);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('HARMONIA RUNHAM','HRUNHAM29', 'HRUNHAM29@TRANSCOMA.COM', 'HARMONIA', '13/02/2015',1);
insert into CLIENTE (_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values ('FERGUSON BRIDAL','FBRIDAL2A', 'FBRIDAL2A@TRANSCOMA.COM', 'FERGUSON', '04/08/2005',1);
insert into CLIENTE (_id,_nombre,_nombreUsuario, _correo, _password, _fechaRegistro, _fkAdminCliente) values (2,'AGOSTO SNADDEN','ASNADDEN2B', 'ASNADDEN2B@TRANSCOMA.COM', 'AGOSTO', '14/10/2018',1);

-- Inserciones para Aduana
insert into ADUANA (_codigo,_nombre) values ('0707','IBIZA AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('0811','BARCELONA MARITIMA IMP.');
insert into ADUANA (_codigo,_nombre) values ('0855','BARCELONA DESPACHO CENTRALIZADO');
insert into ADUANA (_codigo,_nombre) values ('1041','CACERES CARRETERA');
insert into ADUANA (_codigo,_nombre) values ('1175','ALGECIRAS DESPACHO CENTRALIZADO');
insert into ADUANA (_codigo,_nombre) values ('1400','CORDOBA ADM.PROV.ADUANAS E IE.');
insert into ADUANA (_codigo,_nombre) values ('1501','LA CORUÑA AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('1511','LA CORUÑA MARITIMA');
insert into ADUANA (_codigo,_nombre) values ('1741','LA JUNQUERA');
insert into ADUANA (_codigo,_nombre) values ('2045','IRUN ZAISA');
insert into ADUANA (_codigo,_nombre) values ('2700','LUGO ADM.PROV ADUANAS E IE.');
insert into ADUANA (_codigo,_nombre) values ('2871','MADRID FF.CC.');
insert into ADUANA (_codigo,_nombre) values ('3310','GIJON ADM.PROV.ADUANAS E IE.');
insert into ADUANA (_codigo,_nombre) values ('3631','VILLAGARCIA MARITIMA');
insert into ADUANA (_codigo,_nombre) values ('3651','VILLAGARCIA CARRETERA');
insert into ADUANA (_codigo,_nombre) values ('3741','SALAMANCA CARRETERA');
insert into ADUANA (_codigo,_nombre) values ('3900','SANTANDER ADM.PRO.AD.E IE');
insert into ADUANA (_codigo,_nombre) values ('4111','SEVILLA MARÍTIMA');
insert into ADUANA (_codigo,_nombre) values ('4171','SEVILLA FF.CC');
insert into ADUANA (_codigo,_nombre) values ('4241','SORIA');
insert into ADUANA (_codigo,_nombre) values ('4371','TARRAGONA FF.CC.');
insert into ADUANA (_codigo,_nombre) values ('4874','BILBAO POSTALES');

------------HASTA AQUI PARA EFECTOS DE PRUEBA ------------------------------
/*insert into ADUANA (_codigo,_nombre) values ('5503','CEUTA HELIPUERTO');
insert into ADUANA (_codigo,_nombre) values ('5611','MELILLA MARITIMA');
insert into ADUANA (_codigo,_nombre) values ('1110','JEREZ ADM.PROV.ADUANAS IE.');
insert into ADUANA (_codigo,_nombre) values ('1710','LA JUNQUERA ADM.ADUAN. E IE');
insert into ADUANA (_codigo,_nombre) values ('2650','HARO ADM.ADUANAS E II.EE.');
insert into ADUANA (_codigo,_nombre) values ('1710','LA JUNQUERA ADM.ADUAN. E IE');
insert into ADUANA (_codigo,_nombre) values ('0401','ALMERIA AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('0717','ALCUDIA MARITIMA');
insert into ADUANA (_codigo,_nombre) values ('0803','BARCELONA AER.POSTALES');
insert into ADUANA (_codigo,_nombre) values ('1841','MOTRIL CARRETERA');
insert into ADUANA (_codigo,_nombre) values ('2001','GUIPUZCOA AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('2711','RIBADEO MARITIMA');
insert into ADUANA (_codigo,_nombre) values ('2800','MADRID ADM.PROV.ADUANAS E IE.');
insert into ADUANA (_codigo,_nombre) values ('2901','MALAGA AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('3021','CARTAGENA DEP.FRANCO');
insert into ADUANA (_codigo,_nombre) values ('3600','PONTEVEDRA A.PROV.AD.E IE');
insert into ADUANA (_codigo,_nombre) values ('3871','LA PALMA AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('4114','SEVILLA POSTALES');
insert into ADUANA (_codigo,_nombre) values ('5004','ZARAGOZA POSTALES');
insert into ADUANA (_codigo,_nombre) values ('1800','GRANADA ADM.PROV.ADUANAS E IE');
insert into ADUANA (_codigo,_nombre) values ('2200','HUESCA ADM.PROV.ADUAN. E IE');
insert into ADUANA (_codigo,_nombre) values ('3063','BLANCA AB.EXPEDIDORES');
insert into ADUANA (_codigo,_nombre) values ('0500','AVILA.ADM.PROV.ADUANAS IE.');
insert into ADUANA (_codigo,_nombre) values ('0541','AVILA FACTORÍAS');
insert into ADUANA (_codigo,_nombre) values ('0814','BARCELONA MAR.E.VERDE');
insert into ADUANA (_codigo,_nombre) values ('1247','CASTELLON CARRETERA FRUTA');
insert into ADUANA (_codigo,_nombre) values ('1341','CIUDAD REAL');
insert into ADUANA (_codigo,_nombre) values ('1541','LA CORUÑA CARRETERA');
insert into ADUANA (_codigo,_nombre) values ('1700','GERONA ADM.ADUAN. E IE');
insert into ADUANA (_codigo,_nombre) values ('0301','ALICANTE AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('0708','MAHON AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('1711','PALAMOS');
insert into ADUANA (_codigo,_nombre) values ('1841','MOTRIL CARRETERA');
insert into ADUANA (_codigo,_nombre) values ('2045','IRUN ZAISA');
insert into ADUANA (_codigo,_nombre) values ('2111','HUELVA MARITINA');
insert into ADUANA (_codigo,_nombre) values ('2555','LLEIDA, DESPACHO CENTRALIZADO');
insert into ADUANA (_codigo,_nombre) values ('2600','LOGRO?O ADM.PROV ADUANAS E IE.');
insert into ADUANA (_codigo,_nombre) values ('3010','CARTAGENA ADM.PROV.ADUANA IE.');
insert into ADUANA (_codigo,_nombre) values ('3011','CARTAGENA MARITIMA');
insert into ADUANA (_codigo,_nombre) values ('3700','SALAMANCA ADM.PROV.AD.E IE');
insert into ADUANA (_codigo,_nombre) values ('3883','SANTA CRUZ DE T. AEROPUERTO NORTE');
insert into ADUANA (_codigo,_nombre) values ('4101','SEVILLA AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('4171','SEVILLA FF.CC.');
insert into ADUANA (_codigo,_nombre) values ('4601','VALENCIA AEROPUERTO');
insert into ADUANA (_codigo,_nombre) values ('4621','SAGUNTO MARITIMA');
insert into ADUANA (_codigo,_nombre) values ('4874','BILBAO POSTALES');
insert into ADUANA (_codigo,_nombre) values ('5004','ZARAGOZA POSTALES');
insert into ADUANA (_codigo,_nombre) values ('2650','HARO ADM.ADUANAS E II.EE.');
insert into ADUANA (_codigo,_nombre) values ('4320','S.CARLOS DE LA RAPITA ADM.');
insert into ADUANA (_codigo,_nombre) values ('0814','BARCELONA MAR.E.VERDE');
*/

-- Inserciones para Almacen
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('FROTEIS','VIGO-PONTEVEDRA-ESPAÑA',1);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('TAAN COMERC','BARCELONA-ESPAÑA',2);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('COTRANSA - CONTRATACIÓN DE TRANSPORTES SABADELL S.L.','BARCELONA',3);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ICUSTOMS24','HOSPITALET DE LLOBREGAT',4);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('HITSEIN CUSTOMS & EXCISE','BARCELONA',5);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('AUSAN, ALMACÉN Y TRANSPORTE, S.L.','BENIPARREL-VALENCIA',6);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VICENTE MILARA','MONTORNES DEL VALLES.-(BARCELONA)',7);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('PROVEES S.L.','ZIRANDA DE EBRO',8);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('LAMAIGNERE CARGO S.L.','SEVILLA',9);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CANTABRIASIL S.A.','LAS PALMAS DE GRAN CANARIA',10);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('GRANINTRA SA','LAS PALMAS DE GRAN CANARIA',11);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('TMALCUDIA TARRAGONA SRL.','ALGECIRAS',12);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CIRAC LOGÍSTICA','ZARAGOZA',13);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('IRIS CARGO SL','ALGECIRAS',14);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('EXTERNALIZACION DE PROCESOS LOGISTICOS - BERGÉ','BARCELONA',15);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CREMADES, S.L.','VALENCIA',16);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('MEDITERRANEA FORWARDING,SA','MURCIA',17);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ENLACE LOGISTICO INTERNACIONAL','SAN FERNANDO DE HENARES-MADRID',2);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('IPARLA Y ARAMBURU, SL','IRUN',19);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VIORVI S.A','BARCELONA',20);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ITD CONSIGNACIONES,S.L','VIGO PONTEVEDRA',21);
--
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('FROTEIS','VIGO-PONTEVEDRA-ESPAÑA',1);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('TAAN COMERC','BARCELONA-ESPAÑA',2);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('COTRANSA - CONTRATACIÓN DE TRANSPORTES SABADELL S.L.','BARCELONA',3);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ICUSTOMS24','HOSPITALET DE LLOBREGAT',4);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('HITSEIN CUSTOMS & EXCISE','BARCELONA',5);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('AUSAN, ALMACÉN Y TRANSPORTE, S.L.','BENIPARREL-VALENCIA',6);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VICENTE MILARA','MONTORNES DEL VALLES.-(BARCELONA)',7);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('PROVEES S.L.','ZIRANDA DE EBRO',8);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('LAMAIGNERE CARGO S.L.','SEVILLA',9);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CANTABRIASIL S.A.','LAS PALMAS DE GRAN CANARIA',10);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('GRANINTRA SA','LAS PALMAS DE GRAN CANARIA',11);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('TMALCUDIA TARRAGONA SRL.','ALGECIRAS',12);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CIRAC LOGÍSTICA','ZARAGOZA',13);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('IRIS CARGO SL','ALGECIRAS',14);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('EXTERNALIZACION DE PROCESOS LOGISTICOS - BERGÉ','BARCELONA',15);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CREMADES, S.L.','VALENCIA',16);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('MEDITERRANEA FORWARDING,SA','MURCIA',17);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ENLACE LOGISTICO INTERNACIONAL','SAN FERNANDO DE HENARES-MADRID',2);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('IPARLA Y ARAMBURU, SL','IRUN',19);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VIORVI S.A','BARCELONA',20);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ITD CONSIGNACIONES,S.L','VIGO PONTEVEDRA',21);
--
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('FROTEIS','VIGO-PONTEVEDRA-ESPAÑA',1);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('TAAN COMERC','BARCELONA-ESPAÑA',2);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('COTRANSA - CONTRATACIÓN DE TRANSPORTES SABADELL S.L.','BARCELONA',3);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ICUSTOMS24','HOSPITALET DE LLOBREGAT',4);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('HITSEIN CUSTOMS & EXCISE','BARCELONA',5);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('AUSAN, ALMACÉN Y TRANSPORTE, S.L.','BENIPARREL-VALENCIA',6);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VICENTE MILARA','MONTORNES DEL VALLES.-(BARCELONA)',7);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('PROVEES S.L.','ZIRANDA DE EBRO',8);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('LAMAIGNERE CARGO S.L.','SEVILLA',9);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CANTABRIASIL S.A.','LAS PALMAS DE GRAN CANARIA',10);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('GRANINTRA SA','LAS PALMAS DE GRAN CANARIA',11);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('TMALCUDIA TARRAGONA SRL.','ALGECIRAS',12);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CIRAC LOGÍSTICA','ZARAGOZA',13);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('IRIS CARGO SL','ALGECIRAS',14);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('EXTERNALIZACION DE PROCESOS LOGISTICOS - BERGÉ','BARCELONA',15);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('CREMADES, S.L.','VALENCIA',16);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('MEDITERRANEA FORWARDING,SA','MURCIA',17);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ENLACE LOGISTICO INTERNACIONAL','SAN FERNANDO DE HENARES-MADRID',2);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('IPARLA Y ARAMBURU, SL','IRUN',19);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VIORVI S.A','BARCELONA',20);
--
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ITD CONSIGNACIONES,S.L','VIGO PONTEVEDRA',21);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('FROTEIS','VIGO-PONTEVEDRA-ESPAÑA',1);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('TAAN COMERC','BARCELONA-ESPAÑA',2);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('COTRANSA - CONTRATACIÓN DE TRANSPORTES SABADELL S.L.','BARCELONA',3);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ICUSTOMS24','HOSPITALET DE LLOBREGAT',4);
--
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('FROTEIS','VIGO-PONTEVEDRA-ESPAÑA',1);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('TAAN COMERC','BARCELONA-ESPAÑA',2);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('COTRANSA - CONTRATACIÓN DE TRANSPORTES SABADELL S.L.','BARCELONA',3);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ICUSTOMS24','HOSPITALET DE LLOBREGAT',4);
--
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ICUSTOMS24','HOSPITALET DE LLOBREGAT',4);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('HITSEIN CUSTOMS & EXCISE','BARCELONA',5);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('AUSAN, ALMACÉN Y TRANSPORTE, S.L.','BENIPARREL-VALENCIA',6);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VICENTE MILARA','MONTORNES DEL VALLES.-(BARCELONA)',7);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ICUSTOMS24','HOSPITALET DE LLOBREGAT',4);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('HITSEIN CUSTOMS & EXCISE','BARCELONA',5);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('AUSAN, ALMACÉN Y TRANSPORTE, S.L.','BENIPARREL-VALENCIA',6);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VICENTE MILARA','MONTORNES DEL VALLES.-(BARCELONA)',7);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('ICUSTOMS24','HOSPITALET DE LLOBREGAT',4);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('HITSEIN CUSTOMS & EXCISE','BARCELONA',5);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('AUSAN, ALMACÉN Y TRANSPORTE, S.L.','BENIPARREL-VALENCIA',6);
insert into ALMACEN (_nombreAlmacen,_direccion,_fkAduanaAlmacen) values ('VICENTE MILARA','MONTORNES DEL VALLES.-(BARCELONA)',7);


-- INSERCIONES ENTRADAS
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/03/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/07/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/11/2017',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/03/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/03/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('13/11/2017',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('18/12/2017',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/10/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/07/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/05/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/05/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('13/02/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('10/04/2018',1);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/07/2018',2);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('09/01/2018',2);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/07/2018',2);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('04/12/2017',2);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('11/11/2017',2);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/10/2017',2);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('08/04/2018',2);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/03/2018',2);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('18/01/2018',3);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/05/2018',3);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('10/08/2018',3);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/07/2018',3);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/12/2017',3);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('09/05/2018',3);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('12/05/2018',3);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/03/2018',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/11/2017',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/12/2017',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/07/2018',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/10/2017',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/09/2018',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('18/10/2017',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/11/2017',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/06/2018',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/09/2018',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('09/09/2018',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/11/2017',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('15/05/2018',4);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('04/07/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/02/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('15/10/2017',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/04/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/03/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('29/05/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/04/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/04/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/12/2017',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/07/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('24/11/2017',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/11/2017',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/03/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/03/2018',5);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/01/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/03/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('13/01/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/05/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/01/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/08/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('08/03/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('12/06/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('24/10/2017',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/11/2017',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/08/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/06/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/08/2018',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('18/10/2017',6);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('23/12/2017',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('08/11/2017',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/05/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/04/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/09/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('24/07/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/04/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/04/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/12/2017',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/04/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/06/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/04/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('01/06/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/05/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/04/2018',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/11/2017',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/11/2017',7);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('31/05/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/01/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/06/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('11/02/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/09/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/07/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/04/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/12/2017',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/01/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/03/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/08/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('20/05/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/04/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/12/2017',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/04/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/06/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/04/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('01/06/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/05/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/04/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/11/2017',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/11/2017',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('31/05/2018',8);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/01/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/06/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('11/02/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/09/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/07/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/04/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/12/2017',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/01/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/03/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/08/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('20/05/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/04/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/12/2017',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/04/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/06/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/04/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('01/06/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/05/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/04/2018',9);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/11/2017',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/11/2017',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('31/05/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/01/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/06/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('11/02/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/09/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/07/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/04/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/12/2017',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/01/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/03/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/08/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('20/05/2018',10);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/03/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/07/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/11/2017',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/03/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/03/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('13/11/2017',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('18/12/2017',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/10/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/07/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/05/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/05/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('13/02/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('10/04/2018',11);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/07/2018',12);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('09/01/2018',12);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/07/2018',12);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('04/12/2017',12);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('11/11/2017',12);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/10/2017',12);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('08/04/2018',12);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/03/2018',12);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('18/01/2018',13);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/05/2018',13);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('10/08/2018',13);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/07/2018',13);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/12/2017',13);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('09/05/2018',13);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('12/05/2018',13);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/03/2018',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/11/2017',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/12/2017',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/07/2018',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/10/2017',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/09/2018',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('18/10/2017',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/11/2017',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/06/2018',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/09/2018',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('09/09/2018',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/11/2017',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('15/05/2018',14);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('04/07/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/02/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('15/10/2017',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/04/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/03/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('29/05/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/04/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/04/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/12/2017',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/07/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('24/11/2017',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/11/2017',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/03/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/03/2018',15);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/01/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/03/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('13/01/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/05/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/01/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/08/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('08/03/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('12/06/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('24/10/2017',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/11/2017',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/08/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('03/06/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/08/2018',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('18/10/2017',16);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('23/12/2017',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('08/11/2017',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('25/05/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/04/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/09/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('24/07/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/04/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/04/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/12/2017',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/04/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/06/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/04/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('01/06/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/05/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/04/2018',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/11/2017',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/11/2017',17);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('31/05/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/01/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/06/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('11/02/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/09/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/07/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/04/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/12/2017',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/01/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/03/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/08/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('20/05/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/04/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/12/2017',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/04/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/06/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/04/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('01/06/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/05/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/04/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/11/2017',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/11/2017',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('31/05/2018',18);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/01/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/06/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('11/02/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/09/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/07/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/04/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/12/2017',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/01/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/03/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/08/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('20/05/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/04/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/12/2017',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('06/04/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('27/06/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/04/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('01/06/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('05/05/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('02/04/2018',19);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('28/11/2017',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('21/11/2017',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('31/05/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/01/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('30/06/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('11/02/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('26/09/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/07/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('14/04/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('17/12/2017',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('16/01/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('19/03/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('22/08/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('07/02/2018',20);
insert into ENTRADA (_fechaEntrada,_fkAlmacenEntrada) values ('20/05/2018',20);

-- INSERCIONES SALIDAS
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/04/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/08/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('29/11/2017',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('09/03/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/04/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('13/12/2017',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('18/01/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('20/10/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('24/07/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/06/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/08/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('13/04/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('10/05/2018',1);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/09/2018',2);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('09/04/2018',2);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/08/2018',2);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('04/01/2018',2);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/11/2017',2);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/11/2017',2);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('08/06/2018',2);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/04/2018',2);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('18/02/2018',3);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/07/2018',3);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('10/09/2018',3);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/09/2018',3);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/02/2018',3);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('09/08/2018',3);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('12/08/2018',3);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/05/2018',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/12/2017',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/01/2018',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/08/2018',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/10/2017',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/09/2018',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('18/10/2017',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/11/2017',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/06/2018',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/09/2018',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('09/09/2018',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/11/2017',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('15/05/2018',4);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('04/07/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/02/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('15/10/2017',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/04/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/03/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('29/05/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/04/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/04/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/12/2017',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/07/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('24/11/2017',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/11/2017',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/03/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/03/2018',5);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/01/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/03/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('13/01/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/05/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/01/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/08/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('08/03/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('12/06/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('24/10/2017',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/11/2017',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/08/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/06/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/08/2018',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('18/10/2017',6);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('23/12/2017',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('08/11/2017',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/05/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/04/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/09/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('24/07/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/04/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/04/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/12/2017',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/04/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/06/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/04/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('01/06/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/05/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/04/2018',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/11/2017',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/11/2017',7);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('31/05/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/01/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/06/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('11/02/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/09/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/07/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/04/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/12/2017',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/01/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/03/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/08/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('20/05/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/04/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/12/2017',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/04/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/06/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/04/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('01/06/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/05/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/04/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/11/2017',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/11/2017',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('31/05/2018',8);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/01/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/06/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('11/02/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/09/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/07/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/04/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/12/2017',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/01/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/03/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/08/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('20/05/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/04/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/12/2017',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/04/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/06/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/04/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('01/06/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/05/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/04/2018',9);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/11/2017',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/11/2017',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('31/05/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/01/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/06/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('11/02/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/09/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/07/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/04/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/12/2017',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/01/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/03/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/08/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('20/05/2018',10);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/03/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/07/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/11/2017',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/03/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/03/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('13/11/2017',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('18/12/2017',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/10/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/07/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/05/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/05/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('13/02/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('10/04/2018',11);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/07/2018',12);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('09/01/2018',12);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/07/2018',12);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('04/12/2017',12);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('11/11/2017',12);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/10/2017',12);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('08/04/2018',12);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/03/2018',12);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('18/01/2018',13);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/05/2018',13);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('10/08/2018',13);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/07/2018',13);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/12/2017',13);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('09/05/2018',13);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('12/05/2018',13);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/03/2018',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/11/2017',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/12/2017',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/07/2018',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/10/2017',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/09/2018',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('18/10/2017',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/11/2017',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/06/2018',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/09/2018',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('09/09/2018',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/11/2017',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('15/05/2018',14);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('04/07/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/02/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('15/10/2017',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/04/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/03/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('29/05/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/04/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/04/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/12/2017',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/07/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('24/11/2017',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/11/2017',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/03/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/03/2018',15);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/01/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/03/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('13/01/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/05/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/01/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/08/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('08/03/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('12/06/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('24/10/2017',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/11/2017',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/08/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('03/06/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/08/2018',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('18/10/2017',16);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('23/12/2017',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('08/11/2017',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('25/05/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/04/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/09/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('24/07/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/04/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/04/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/12/2017',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/04/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/06/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/04/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('01/06/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/05/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/04/2018',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/11/2017',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/11/2017',17);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('31/05/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/01/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/06/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('11/02/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/09/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/07/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/04/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/12/2017',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/01/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/03/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/08/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('20/05/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/04/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/12/2017',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/04/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/06/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/04/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('01/06/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/05/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/04/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/11/2017',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/11/2017',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('31/05/2018',18);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/01/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/06/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('11/02/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/09/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/07/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/04/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/12/2017',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/01/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/03/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/08/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/02/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('20/05/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/04/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/12/2017',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('06/04/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('27/06/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/04/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('01/06/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('05/05/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('02/06/2018',19);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('28/12/2017',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('21/12/2017',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/06/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/02/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('30/09/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('11/03/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('26/10/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/08/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/06/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('14/06/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('17/12/2017',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('16/04/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('19/06/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('22/09/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('07/03/2018',20);
insert into SALIDA (_fechaSalida,_fkAlmacenSalida) values ('20/06/2018',20);



------------------------------------INSERTS DIRECCION-----------------------------------------------------
INSERT INTO DIRECCION(_codigozip, _ciudad, _provincia, _estado, _pais) VALUES ('08','BARCELONA', 'PROVINCIA BARCELONA','BARCELONA','ESPAÑA');
INSERT INTO DIRECCION(_codigozip, _ciudad, _provincia, _estado, _pais) VALUES ('46001','VALENCIA', 'PROVINCIA VALENCIA','VALENCIA','ESPAÑA');
INSERT INTO DIRECCION(_codigozip, _ciudad, _provincia, _estado, _pais) VALUES ('4603','MADRID', 'PROVINCIA MADRID','MADRID','ESPAÑA');


------------------------------------INSERTS PUERTO----------------------------------------------------------
INSERT INTO PUERTO(_codigo, _nombre, _fkdireccion) VALUES ('001','PUERTO DE BARCELONA',1);
INSERT INTO PUERTO(_codigo, _nombre, _fkdireccion) VALUES ('002','PUERTO DE VALENCIA',2);
INSERT INTO PUERTO(_codigo, _nombre, _fkdireccion) VALUES ('003','PUERTO DE MADRID',3);

------------------------------------INSERTS TIPO_CONTAINER-------------------------------------------------
INSERT INTO TIPO_CONTAINER(_nombre, _tarifa, _dimension, _alto, _ancho, _profundidad, _tipo)
VALUES ('20 PIES',100, 'pies', 20, 8, 8.6,'completo');
INSERT INTO TIPO_CONTAINER(_nombre, _tarifa, _dimension, _alto, _ancho, _profundidad, _tipo)
VALUES ('40 PIES',200, 'pies', 40, 8, 8.6,'completo');
INSERT INTO TIPO_CONTAINER(_nombre, _tarifa, _dimension, _alto, _ancho, _profundidad, _tipo)
VALUES ('40 PIES HC',300, 'pies', 40, 8, 9.6,'completo');
INSERT INTO TIPO_CONTAINER(_nombre, _tarifa, _dimension,_tipo)
VALUES ('LCL',50, 'pies','compartido');

------------------------------------INSERTS EMBARQUE---------------------------------------------------------
INSERT INTO EMBARQUE(_puertoEmbarque, _puertoRecepcion, _fechaSalida, _duracion) VALUES (1,2,'08/11/2018',4);
INSERT INTO EMBARQUE(_puertoEmbarque, _puertoRecepcion, _fechaSalida, _duracion) VALUES (2,1,'15/11/2018',4);
INSERT INTO EMBARQUE(_puertoEmbarque, _puertoRecepcion, _fechaSalida, _duracion) VALUES (2,3,'17/11/2018',5);

------------------------------------INSERTS COTIZACION------------------------------------------------------
INSERT INTO COTIZACION(_flete, _recargo, _gastosAdmin, _fechaSalida, _duracion, _total) VALUES (45,10,485,'15/11/2018',5,540);
INSERT INTO COTIZACION(_flete, _recargo, _gastosAdmin, _fechaSalida, _duracion, _total) VALUES (25,10,485,'11/11/2018',5,520);

-------------------------------------INSERTS CONTAINER--------------------------------------------
INSERT INTO CONTAINER(_numBultos, _fkTipoContainer, _fkcotizacion) VALUES (56,1,1);

-------------------------------------INSERTS BL---------------------------------------------------
INSERT INTO BL(_notifyParty,_lugarRecepcion, _buqueoceno, _fkpol, _fkpod, _lugarEntrega, _fletepagoen,
               _numpaquetes, _descripcion, _pesocarga, _fkcotizacion, _fkcliente, _volumen)
VALUES ('A LORDRE DE
ALGERIA GOLF BANK
', 'BARCELONA','Vessel',1,2,'BARCELONA','ORIGIN',2,'S.T.C. - 24 PACKG MARCHE Nº23/2014-REALISATION ET EXPLOITATION DE LA STATION', 100, 1,1,300)
